export const events = [
  // Apr 3
  {
    day: "Apr 3",
    time: "8:00 AM",
    loc: "Auditorium D",
    club: "TONEELSTUK",
    name: "Adakari",
    desc: "Ek Chehra, Kai Kirdaar. Win hearts not just rewards. The spotlight is the real prize.",
    tags: ["creative", "performing"],
    regLink: "https://forms.gle/rrDM48KRQys2SePXA",
  },
  {
    day: "Apr 3",
    time: "8:00 AM",
    loc: "E-Block Lawn",
    club: "SOA FLYING COMMUNITY",
    name: "Aero Innovation",
    desc: "Pilot a hovercraft across mixed terrain navigating obstacles.",
    tags: ["technical", "sports"],
    regLink: "https://forms.gle/PkSf2z53TY9ugiY66",
  },
  {
    day: "Apr 3",
    time: "8:00 AM",
    loc: "E-314 & E-321",
    club: "SOA RADIO CLUB",
    name: "Asli Dhurandhar Kaun?",
    desc: "Strangers become teams in every round...",
    tags: ["sports", "creative"],
    regLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSd5BplXXXwLiNqQK7Ant1Duppef713OE2uVr6KDbEcK-zlg-A/viewform",
  },
  {
    day: "Apr 3",
    time: "8:00 AM",
    loc: "E-214",
    club: "SOA PHOTOGRAPHY CLUB",
    name: "Captured Narratives",
    desc: "Shoot and edit a series of 10–15 images to tell a visual story.",
    tags: ["creative"],
    regLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSfbdXVawV2BWs3Y-H9s32ZljmcYE_8wgcm9kpcaoku6T80Aaw/viewform",
  },
  {
    day: "Apr 3",
    time: "8:00 AM",
    loc: "Auditorium C",
    club: "SRISHTI",
    name: "Earthen Expressions",
    desc: "A Pot Painting Competition.",
    tags: ["creative"],
    regLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSdPBqsqKXqZdXHTgefzyT__ba28bxx9CkIMp9c2FGSH_s4VZg/viewform",
  },
  {
    day: "Apr 3",
    time: "8:00 AM",
    loc: "E-514",
    club: "SOA ENGLISH CAFE",
    name: "Medha Manthan",
    desc: "Individual quiz testing presence of mind.",
    tags: ["technical"],
    regLink: "https://forms.gle/fyyLKu2Z1Aog3JQp6",
  },
  {
    day: "Apr 3",
    time: "8:00 AM",
    loc: "ITER Campus",
    club: "JAAGO",
    name: "Play Fest",
    desc: "Mini games with friends.",
    tags: ["sports"],
    regLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSfOq93BH_fcWnO75E1qHFPjAArt1kAqJuoj8kXnhEsF_UTpTA/viewform",
  },
  {
    day: "Apr 3",
    time: "8:00 AM",
    loc: "E-Block Gallery",
    club: "ITER ROBOTICS CLUB",
    name: "Robo Race",
    desc: "Build and race a robot.",
    tags: ["technical"],
    regLink: "https://chakravyuh.iterroboticsclub.com/",
  },
  {
    day: "Apr 3",
    time: "8:00 AM",
    loc: "E-114",
    club: "IEC",
    name: "The ScratchLabs",
    desc: "Startup simulation.",
    tags: ["technical"],
    regLink: "https://www.ecellsoa.in/scratchlabs",
  },
  {
    day: "Apr 3",
    time: "8:00 AM",
    loc: "Lab",
    club: "GEEKSFORGEEKS",
    name: "ZerOne",
    desc: "CTF event.",
    tags: ["technical"],
    regLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSfD9PRA9bLdxP-27C_gFCUIGQ7ZwfkQHqdjHYcAZM946joSTw/viewform",
  },

  // Apr 3 (11:30)
  {
    day: "Apr 3",
    time: "11:30 AM",
    loc: "E-114",
    club: "CODING NINJAS × SLC",
    name: "Hypocrisy 2.0",
    desc: "Turn-Coat Debate.",
    tags: ["creative"],
    regLink: "https://forms.gle/wK1a6ZsYs2wGEmts7",
  },
  {
    day: "Apr 3",
    time: "11:30 AM",
    loc: "E-114",
    club: "SOA LITERARY CLUB",
    name: "Hypocrisy ki bhi seema hoti hai 2.0",
    desc: "Turn-Coat Debate.",
    tags: ["creative"],
    regLink: "https://forms.gle/wK1a6ZsYs2wGEmts7",
  },
  {
    day: "Apr 3",
    time: "11:30 AM",
    loc: "Auditorium A",
    club: "VOGUE",
    name: "Mr. and Miss ITER",
    desc: "Fashion competition.",
    tags: ["fashion"],
    regLink: "https://forms.gle/NRxgUmQPDqmMRgx88",
  },

  // Apr 4
  {
    day: "Apr 4",
    time: "8:00 AM",
    loc: "Auditorium C & D",
    club: "GDGSC",
    name: "AI Treasure Hunt",
    desc: "Tech challenge.",
    tags: ["technical"],
    regLink: "https://forms.gle/TReLtKGQvyi9Aa8W6",
  },
  {
    day: "Apr 4",
    time: "8:00 AM",
    loc: "E-314 & LAB",
    club: "SOA ENGLISH CAFE × CODEX",
    name: "Anant Chakra",
    desc: "AI systems challenge.",
    tags: ["technical"],
    regLink: "https://forms.gle/vsjwj4S3ViPuq9A56",
  },
  {
    day: "Apr 4",
    time: "8:00 AM",
    loc: "E-013",
    club: "VS",
    name: "CineFolie",
    desc: "Video challenge.",
    tags: ["creative"],
    regLink: "https://forms.gle/AzZNaPHnAsFKCYfU6",
  },
  {
    day: "Apr 4",
    time: "8:00 AM",
    loc: "E-Block Lawn",
    club: "SOA RADIO CLUB",
    name: "Dart-E-Dil Returns",
    desc: "Fun challenge.",
    tags: ["sports"],
    regLink:
      "https://docs.google.com/forms/d/e/1FAIpQLScn5T6V4c6dPucJfCwuedQurWL143vNkmzUmJM7gTPLGWGCoQ/viewform",
  },
  {
    day: "Apr 4",
    time: "8:00 AM",
    loc: "E-414",
    club: "VOGUE",
    name: "Fashion Face-Off",
    desc: "Design competition.",
    tags: ["fashion"],
    regLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSfWhsoYQcRrIcg_xeUA5KC0I1XE3VCXaVm8kiXXzYMa-HOjkA/viewform",
  },
  {
    day: "Apr 4",
    time: "8:00 AM",
    loc: "C-Block Gallery",
    club: "SOA FLYING COMMUNITY",
    name: "HoverMania",
    desc: "Drone challenge.",
    tags: ["technical"],
    regLink: "https://forms.gle/JiduigP5AFudrZwn7",
  },
  {
    day: "Apr 4",
    time: "8:00 AM",
    loc: "E-214",
    club: "SOA PHOTOGRAPHY CLUB",
    name: "Motion Mania",
    desc: "Reel making.",
    tags: ["creative"],
    regLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSd7zifmcPRybjhrE5WIdtNDYyrMhdlHyjLlXGF5kmtlIoWXAw/viewform",
  },
  {
    day: "Apr 4",
    time: "8:00 AM",
    loc: "ITER Campus",
    club: "JAAGO",
    name: "Play Fest",
    desc: "Games.",
    tags: ["sports"],
    regLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSfOq93BH_fcWnO75E1qHFPjAArt1kAqJuoj8kXnhEsF_UTpTA/viewform",
  },
  {
    day: "Apr 4",
    time: "8:00 AM",
    loc: "Auditorium A",
    club: "CODING NINJAS",
    name: "Techwiz 3.0",
    desc: "Tech quiz.",
    tags: ["technical"],
    regLink: "https://forms.gle/j6pXM9Wv487WnEKZ6",
  },

  // Apr 4 (11:30)
  {
    day: "Apr 4",
    time: "11:30 AM",
    loc: "Auditorium A",
    club: "DANZA",
    name: "Beat Drop Arena",
    desc: "Dance competition.",
    tags: ["performing"],
    regLink: "https://forms.gle/VCn9V7NGJcRcg3so8",
  },
  {
    day: "Apr 4",
    time: "11:30 AM",
    loc: "LABS",
    club: "IEEE",
    name: "Spinotage",
    desc: "Technical challenge.",
    tags: ["technical"],
    regLink:
      "https://docs.google.com/forms/d/e/1FAIpQLSerp8ENecoMA6Ps31wnAQ41j92CJtEaEdH4c-xbq6D7q5xamw/viewform",
  },

  // Apr 5 (partial — rest same pattern)
  {
    day: "Apr 5",
    time: "8:00 AM",
    loc: "C-Block Gallery",
    club: "DANZA",
    name: "Apex Arena",
    desc: "Dance battle.",
    tags: ["performing"],
    regLink: "https://forms.gle/gPztEAjhfp2V8yoR8",
  },
  {
    day: "Apr 5",
    time: "8:00 AM",
    loc: "E-Block Gallery",
    club: "ITER ROBOTICS CLUB",
    name: "Bot FC",
    desc: "Robot football.",
    tags: ["technical"],
    regLink: "https://chakravyuh.iterroboticsclub.com/",
  },
  {
    day: "Apr 5",
    time: "8:00 AM",
    loc: "LABS",
    club: "CODEX",
    name: "Coders in Borderland",
    desc: "Coding challenge.",
    tags: ["technical"],
    regLink: "https://forms.gle/aQTy71dWyf5YQpiT6",
  },
];

export const days = ["Apr 3", "Apr 4", "Apr 5"];

export const dayNums = {
  "Apr 3": 1,
  "Apr 4": 2,
  "Apr 5": 3,
};

export const dayColors = {
  1: "#e8c547",
  2: "#e05a2b",
  3: "#5b8fff",
};
