export const events = [
  // Apr 3
  {
    day: "Apr 3",
    time: "8:00 AM",
    loc: "Auditorium D",
    club: "TONEELSTUK",
    name: "Adakari",
    desc: "Ek Chehra, Kai Kirdaar. Win hearts not just rewards. The spotlight is the real prize.",
    tags: ["creative", "performing"],
  },
  {
    day: "Apr 3",
    time: "8:00 AM",
    loc: "E-Block Lawn",
    club: "SOA FLYING COMMUNITY",
    name: "Aero Innovation",
    desc: "Pilot a hovercraft across mixed terrain navigating obstacles.",
    tags: ["technical", "sports"],
  },
  {
    day: "Apr 3",
    time: "8:00 AM",
    loc: "E-314 & E-321",
    club: "SOA RADIO CLUB",
    name: "Asli Dhurandhar Kaun?",
    desc: "Strangers become teams in every round — from Who's the Spy to Squid Game and a surprise twist.",
    tags: ["sports", "creative"],
  },
  {
    day: "Apr 3",
    time: "8:00 AM",
    loc: "E-214",
    club: "SOA PHOTOGRAPHY CLUB",
    name: "Captured Narratives",
    desc: "Shoot and edit a series of 10–15 images to tell a visual story.",
    tags: ["creative"],
  },
  {
    day: "Apr 3",
    time: "8:00 AM",
    loc: "Auditorium C",
    club: "SRISHTI",
    name: "Earthen Expressions",
    desc: "A Pot Painting Competition. Individual participation.",
    tags: ["creative"],
  },
  {
    day: "Apr 3",
    time: "8:00 AM",
    loc: "E-514",
    club: "SOA ENGLISH CAFE",
    name: "Medha Manthan",
    desc: "Individual quiz testing presence of mind on GK, arts, and communication.",
    tags: ["technical"],
  },
  {
    day: "Apr 3",
    time: "8:00 AM",
    loc: "ITER Campus",
    club: "JAAGO",
    name: "Play Fest",
    desc: "Surprise miniature challenges of multiple games to enjoy with friends.",
    tags: ["sports"],
  },
  {
    day: "Apr 3",
    time: "8:00 AM",
    loc: "E-Block Gallery",
    club: "ITER ROBOTICS CLUB",
    name: "Robo Race",
    desc: "Build and race a robot through an obstacle-filled track.",
    tags: ["technical"],
  },
  {
    day: "Apr 3",
    time: "8:00 AM",
    loc: "E-114",
    club: "IEC",
    name: "The ScratchLabs",
    desc: "A 2-day startup simulation where teams of two tackle curated problem statements using design thinking.",
    tags: ["technical"],
  },
  {
    day: "Apr 3",
    time: "8:00 AM",
    loc: "Lab",
    club: "GEEKSFORGEEKS",
    name: "ZerOne",
    desc: "A CTF event focused on cyber and data challenges testing real-world problem-solving under pressure.",
    tags: ["technical"],
  },
  {
    day: "Apr 3",
    time: "11:30 AM",
    loc: "E-114",
    club: "CODING NINJAS × SLC",
    name: "Hypocrisy 2.0",
    desc: "A Turn-Coat Debate where teams of two defend and oppose a motion.",
    tags: ["creative"],
  },
  {
    day: "Apr 3",
    time: "11:30 AM",
    loc: "E-114",
    club: "SOA LITERARY CLUB",
    name: "Hypocrisy ki bhi seema hoti hai 2.0",
    desc: "A Turn-Coat Debate where teams of two defend and oppose a motion.",
    tags: ["creative"],
  },
  {
    day: "Apr 3",
    time: "11:30 AM",
    loc: "Auditorium A",
    club: "VOGUE (SOA FASHION CLUB)",
    name: "Mr. and Miss ITER",
    desc: "Personality and talent-based competition involving walk and talent rounds.",
    tags: ["fashion", "performing"],
  },
  // Apr 4
  {
    day: "Apr 4",
    time: "8:00 AM",
    loc: "Auditorium C & D",
    club: "GDGSC",
    name: "AI Treasure Hunt",
    desc: "Location-based challenge to solve riddles and complete tech tasks. Team Size: 3.",
    tags: ["technical"],
  },
  {
    day: "Apr 4",
    time: "8:00 AM",
    loc: "E-314 & LAB",
    club: "SOA ENGLISH CAFE × CODEX",
    name: "Anant Chakra",
    desc: "Agentic AI Systems & Policy Design Challenge.",
    tags: ["technical"],
  },
  {
    day: "Apr 4",
    time: "8:00 AM",
    loc: "E-013",
    club: "VIRTUALSHOWREEL (VS)",
    name: "CineFolie",
    desc: "Theme provided on the spot. Video shot in campus based on theme. Max 5 participants per team.",
    tags: ["creative", "performing"],
  },
  {
    day: "Apr 4",
    time: "8:00 AM",
    loc: "E-Block Lawn",
    club: "SOA RADIO CLUB",
    name: "Dart-E-Dil Returns",
    desc: "Hit the center for the easiest charades, the middle for a fun twist, and the outer ring for the toughest acts!",
    tags: ["sports", "creative"],
  },
  {
    day: "Apr 4",
    time: "8:00 AM",
    loc: "E-414",
    club: "VOGUE (SOA FASHION CLUB)",
    name: "Fashion Face-Off",
    desc: "Competition for designers and makeup artists to showcase complete looks.",
    tags: ["fashion", "creative"],
  },
  {
    day: "Apr 4",
    time: "8:00 AM",
    loc: "C-Block Gallery",
    club: "SOA FLYING COMMUNITY",
    name: "HoverMania",
    desc: "Guide a drone through challenges and drop an egg safely.",
    tags: ["technical", "sports"],
  },
  {
    day: "Apr 4",
    time: "8:00 AM",
    loc: "E-214",
    club: "SOA PHOTOGRAPHY CLUB",
    name: "Motion Mania",
    desc: "60-second vertical video storytelling (Instagram Reel style).",
    tags: ["creative"],
  },
  {
    day: "Apr 4",
    time: "8:00 AM",
    loc: "ITER Campus",
    club: "JAAGO",
    name: "Play Fest",
    desc: "Surprise miniature challenges of multiple games to enjoy with friends.",
    tags: ["sports"],
  },
  {
    day: "Apr 4",
    time: "8:00 AM",
    loc: "Auditorium A",
    club: "CODING NINJAS",
    name: "Techwiz 3.0",
    desc: "Technical quiz and problem-solving event. Final round involves advanced questions.",
    tags: ["technical"],
  },
  {
    day: "Apr 4",
    time: "8:00 AM",
    loc: "E-114",
    club: "IEC",
    name: "The ScratchLabs (Day 2)",
    desc: "Continued 2-day startup simulation — teams present and refine their design-thinking solutions.",
    tags: ["technical"],
  },
  {
    day: "Apr 4",
    time: "11:30 AM",
    loc: "Auditorium A",
    club: "DANZA",
    name: "Beat Drop Arena",
    desc: "Solo-Spectra & Duo-xtra western dance competitions. High-energy rhythmic performance.",
    tags: ["performing"],
  },
  {
    day: "Apr 4",
    time: "11:30 AM",
    loc: "LABS",
    club: "IEEE",
    name: "Spinotage",
    desc: "Technical challenges with unpredictable sabotages testing logic and strategy.",
    tags: ["technical"],
  },
  // Apr 5
  {
    day: "Apr 5",
    time: "8:00 AM",
    loc: "C-Block Gallery",
    club: "DANZA",
    name: "Apex Arena",
    desc: "Solo Dance Battle — the final stage for elite solo dancers.",
    tags: ["performing"],
  },
  {
    day: "Apr 5",
    time: "8:00 AM",
    loc: "E-Block Gallery",
    club: "ITER ROBOTICS CLUB",
    name: "Bot FC",
    desc: "Compete in robotic football where bots battle to score goals.",
    tags: ["technical", "sports"],
  },
  {
    day: "Apr 5",
    time: "8:00 AM",
    loc: "LABS",
    club: "CODEX",
    name: "Coders in Borderland",
    desc: "Story-based technical event testing coding, logic, and strategy.",
    tags: ["technical"],
  },
  {
    day: "Apr 5",
    time: "8:00 AM",
    loc: "E-311",
    club: "VIRTUALSHOWREEL (VS)",
    name: "Color-E-Pic",
    desc: "Capture photos based on a given color theme to make a story. Max 3 participants.",
    tags: ["creative"],
  },
  {
    day: "Apr 5",
    time: "8:00 AM",
    loc: "Lab",
    club: "GDGSC",
    name: "Maya Vyuh: The Prompt War",
    desc: "AI + Communication Challenge recreating images using prompts. Team Size: 2.",
    tags: ["technical", "creative"],
  },
  {
    day: "Apr 5",
    time: "8:00 AM",
    loc: "Auditorium A",
    club: "SOA MUSIC CLUB (SMC)",
    name: "Naghma",
    desc: "Opportunity for singers and instrumentalists to showcase classical or western musical skills.",
    tags: ["performing"],
  },
  {
    day: "Apr 5",
    time: "8:00 AM",
    loc: "Auditorium D",
    club: "SRISHTI",
    name: "Nishaan-e-Hunr",
    desc: "Body-safe sketch and tattoo creating competition.",
    tags: ["creative"],
  },
  {
    day: "Apr 5",
    time: "8:00 AM",
    loc: "Seminar Hall",
    club: "GEEKSFORGEEKS",
    name: "Rachitva",
    desc: "Impromptu design and communication skills competition ending in a professional pitch.",
    tags: ["creative", "technical"],
  },
  {
    day: "Apr 5",
    time: "8:00 AM",
    loc: "E-114",
    club: "SOA LITERARY CLUB",
    name: "ReCast",
    desc: "Twisted Declamation — reimagining well-known pieces with alternate endings.",
    tags: ["creative", "performing"],
  },
  {
    day: "Apr 5",
    time: "8:00 AM",
    loc: "E-522",
    club: "TONEELSTUK",
    name: "Takhleeqi",
    desc: "Character nahi... poora Bollywood moment bano!",
    tags: ["creative", "performing"],
  },
  {
    day: "Apr 5",
    time: "8:00 AM",
    loc: "E-013",
    club: "IEC",
    name: "The AI Tribunal",
    desc: "A courtroom-style simulation where participants debate the ethics, impact, and reality of AI through structured arguments.",
    tags: ["technical", "creative"],
  },
  {
    day: "Apr 5",
    time: "11:00 AM",
    loc: "Auditorium A",
    club: "SOA MUSIC CLUB (SMC)",
    name: "Beatsync",
    desc: "Dynamic platform for participants to showcase hip-hop talents through rap and beatboxing.",
    tags: ["performing"],
  },
  {
    day: "Apr 5",
    time: "12:00 PM",
    loc: "Auditorium A",
    club: "ODANZA",
    name: "Natya Katha",
    desc: "Solo Dance Competition based on storytelling using a mystery prop.",
    tags: ["performing"],
  },
];

export const days = ["Apr 3", "Apr 4", "Apr 5"];

export const dayNums = {
  "Apr 3": 1,
  "Apr 4": 2,
  "Apr 5": 3
};

export const dayColors = {
  1: "#e8c547",
  2: "#e05a2b",
  3: "#5b8fff"
};